export const ATTRIBUTE_NAMES: Attribute[] = [
  "ノーマル" ,
  "ほのお" ,
  "みず" ,
  "でんき" ,
  "くさ" ,
  "こおり" ,
  "かくとう" ,
  "どく" ,
  "じめん" ,
  "ひこう" ,
  "エスパー" ,
  "むし" ,
  "いわ" ,
  "ゴースト" ,
  "ドラゴン" ,
  "あく" ,
  "はがね" ,
  "フェアリー" ,
];

type AttributeAttributes = { abbrev: string };
export const ATTRIBUTES: Record<Attribute, AttributeAttributes> = {
  "ノーマル": { abbrev: "無" },
  "ほのお": { abbrev: "炎" },
  "みず": { abbrev: "水" },
  "でんき": { abbrev: "電" },
  "くさ": { abbrev: "草" },
  "こおり": { abbrev: "氷" },
  "かくとう": { abbrev: "闘" },
  "どく": { abbrev: "毒" },
  "じめん": { abbrev: "地" },
  "ひこう": { abbrev: "飛" },
  "エスパー": { abbrev: "超" },
  "むし": { abbrev: "虫" },
  "いわ": { abbrev: "岩" },
  "ゴースト": { abbrev: "霊" },
  "ドラゴン": { abbrev: "竜" },
  "あく": { abbrev: "悪" },
  "はがね": { abbrev: "鋼" },
  "フェアリー": { abbrev: "妖" },
};
